### ISSUE TITLE
List of all remaining packages to update

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-desktop-full#3]
I just finished what I think completes ros-melodic-ros-base, ros-melodic-desktop, and ros-melodic-desktop-full. There will surely be some adjustments. In the meantime, here are the packages that aren't pulled in by these. I have local branches with automated changes made, but I still need to verify and build them before committing. For now, here's the list!

- [ ] ros-melodic-moveit-ros-planning-interface; **note:** see this [PR](https://github.com/ros-melodic-arch/ros-melodic-moveit-ros-planning-interface/pull/1/files)
- [ ] ros-melodic-bfl; **note**: [upstream](https://github.com/toeklk/orocos-bayesian-filtering/tags) does not have any releases, [only ros-gbp](https://github.com/ros-gbp/bfl-release) so we're stuck
- [ ] ros-melodic-realtime-tools; **note:** unable to build upstream, I think due to [catkin](https://github.com/ros/catkin/issues/1030) or [gmock](https://bugs.archlinux.org/task/63793?project=5&string=gmock)

---

- [x] ros-melodic-tuw-vehicle-msgs
- [x] ros-melodic-urdf-geometry-parser
- [x] ros-melodic-tracetools
- [x] ros-melodic-tuw-nav-msgs
- [x] ros-melodic-tuw-gazebo-msgs
- [x] ros-melodic-wu-ros-tools
- [x] ros-melodic-tuw-msgs
- [x] ros-melodic-tuw-airskin-msgs
- [x] ros-melodic-tuw-object-msgs
- [x] ros-melodic-dynamic-edt-3d
- [x] ros-melodic-easy-markers
- [x] ros-melodic-octovis
- [x] ros-melodic-warehouse-ros
- [x] ros-melodic-audio-common
- [x] ros-melodic-srdfdom
- [x] ros-melodic-audio-common-msgs
- [x] ros-melodic-roslisp-repl
- [x] ros-melodic-slime-wrapper
- [x] ros-melodic-slime-ros
- [x] ros-melodic-rosemacs
- [x] ros-melodic-ros-emacs-utils
- [x] ros-melodic-rgbd-launch
- [x] ros-melodic-octomap
- [x] ros-melodic-ecl-build
- [x] ros-melodic-ecl-concepts
- [x] ros-melodic-ecl-config
- [x] ros-melodic-ecl-errors
- [x] ros-melodic-ecl-exceptions
- [x] ros-melodic-ecl-license
- [x] ros-melodic-ecl-mpl
- [x] ros-melodic-ecl-threads
- [x] ros-melodic-ecl-time
- [x] ros-melodic-ecl-time-lite
- [x] ros-melodic-ecl-type-traits
- [x] ros-melodic-ecl-utilities
- [x] ros-melodic-map-server
- [x] ros-melodic-move-base
- [x] ros-melodic-move-base-msgs
- [x] ros-melodic-moveit-msgs
- [x] ros-melodic-moveit-resources
- [x] ros-melodic-nav-core
- [x] ros-melodic-navfn
- [x] ros-melodic-object-recognition-msgs
- [x] ros-melodic-octomap-msgs
- [x] ros-melodic-pointcloud-to-laserscan
- [x] ros-melodic-robot-localization
- [x] ros-melodic-rotate-recovery
- [x] ros-melodic-voxel-grid
- [x] ros-melodic-yocs-velocity-smoother
- [x] ros-melodic-amcl
- [x] ros-melodic-base-local-planner
- [x] ros-melodic-four-wheel-steering-controller
- [x] ros-melodic-four-wheel-steering-msgs
- [x] ros-melodic-convex-decomposition
- [x] ros-melodic-ivcon
- [x] ros-melodic-pr2-msgs
- [x] ros-melodic-pr2-description
- [x] ros-melodic-pr2-dashboard-aggregator
- [x] ros-melodic-pr2-machine
- [x] ros-melodic-pr2-common
- [x] ros-melodic-socketcan-bridge
- [x] ros-melodic-can-msgs
- [x] ros-melodic-socketcan-interface
- [x] ros-melodic-geographic-msgs
- [x] ros-melodic-libmavconn
- [x] ros-melodic-mavros-extras
- [x] ros-melodic-mavros-msgs
- [x] ros-melodic-test-mavros
- [x] ros-melodic-mavlink
- [x] ros-melodic-mavros
- [x] ros-melodic-costmap-2d
- [x] ros-melodic-moveit-experimental
- [x] ros-melodic-chomp-motion-planner
- [x] ros-melodic-rosmake
- [x] ros-melodic-test-diagnostic-aggregator
- [x] ros-melodic-rosdiagnostic
- [x] ros-melodic-clear-costmap-recovery
- [x] ros-melodic-moveit
- [x] ros-melodic-moveit-commander
- [x] ros-melodic-moveit-fake-controller-manager
- [x] ros-melodic-moveit-kinematics
- [x] ros-melodic-moveit-planners
- [x] ros-melodic-moveit-planners-ompl
- [x] ros-melodic-moveit-plugins
- [x] ros-melodic-moveit-ros
- [x] ros-melodic-moveit-ros-benchmarks
- [x] ros-melodic-moveit-ros-control-interface
- [x] ros-melodic-moveit-ros-manipulation
- [x] ros-melodic-moveit-ros-move-group
- [x] ros-melodic-moveit-ros-perception
- [x] ros-melodic-moveit-ros-planning
- [x] ros-melodic-moveit-ros-robot-interaction
- [x] ros-melodic-moveit-ros-visualization
- [x] ros-melodic-moveit-ros-warehouse
- [x] ros-melodic-moveit-setup-assistant
- [x] ros-melodic-moveit-simple-controller-manager
- [x] ros-melodic-moveit-core
- [x] ros-melodic-joy
- [x] ros-melodic-joy-listener
- [x] ros-melodic-wiimote
- [x] ros-melodic-ps3joy
- [x] ros-melodic-spacenav-node
- [x] ros-melodic-joystick-drivers
- [x] ros-melodic-libuvc-camera
- [x] ros-melodic-libuvc-ros
- [x] ros-melodic-openni-launch; ~**note:** see [issue](https://github.com/ros-melodic-arch/ros-melodic-openni-launch/issues/1)~
- [x] ros-melodic-openni-camera; ~**note:** see [issue](https://github.com/ros-melodic-arch/ros-melodic-openni-camera/issues/1)~
- [x] ros-melodic-openni2-camera; ~**note:** see [issue](https://github.com/ros-melodic-arch/ros-melodic-openni2-camera/issues/1)~
- [x] ros-melodic-openni2-launch; ~**note:** see [issue](https://github.com/ros-melodic-arch/ros-melodic-openni2-launch/issues/1)~

**Comment by jwhendy** [comment]
Bam. Calling this done. Notes are present where I could not update. This should mark the end of migrating all `ros-melodic-*` to upstream sources, bumping `pkver` and `pkgrel` where needed, and verifying builds on my machine.

I'll await @bionade24 's upcoming activity and sync to AUR, then re-build from there to catch an issues, if any. All above packages can be tracked via issues. Closing.

**Comment by bionade24** [comment]
Thanks! I hope I can.build & sync this afternoon.

Am Mittwoch, 18. September 2019 schrieb John Hendy:
